fix(workflows): bump wersion and fix dependabot

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -1,64 +1,64 @@
 name: Unit Verification
 run-name: >-
-    ${{ 
-        github.event_name == 'pull_request' 
-        && format('Unit Test Verification for CI: PR #{0} -> {1}', github.event.number, github.event.pull_request.title)
-        ||
-        github.event_name == 'push'
-        && format('Unit Test Verification for CI: Merge -> {0}', github.event.head_commit.message)
-    }}
+  ${{
+      github.event_name == 'pull_request'
+      && format('Unit Test Verification for CI: PR #{0} -> {1}', github.event.number, github.event.pull_request.title)
+      ||
+      github.event_name == 'push'
+      && format('Unit Test Verification for CI: Merge -> {0}', github.event.head_commit.message)
+  }}
 on:
-    pull_request:
-        types: [opened, synchronize, reopened]
-    push:
-        branches: [ "main" ]
+  pull_request:
+    types: [opened, synchronize, reopened]
+  push:
+    branches: ["main"]
 
 permissions:
-    contents: read
+  contents: read
 
 concurrency:
-    group: ${{ github.event_name == 'pull_request' && format('{0}-pr-{1}', github.workflow, github.event.pull_request.number) || format('{0}-ref-{1}', github.workflow, github.ref) }}
-    cancel-in-progress: true
+  group: ${{ github.event_name == 'pull_request' && format('{0}-pr-{1}', github.workflow, github.event.pull_request.number) || format('{0}-ref-{1}', github.workflow, github.ref) }}
+  cancel-in-progress: true
 
 jobs:
-    unit-ci-test:
-        name: Testing
-        runs-on: ubuntu-latest
-        timeout-minutes: 30
+  unit-ci-test:
+    name: Testing
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
 
-        steps:
-        - name: 📥 Git -- Checkout repository
-          uses: actions/checkout@v6
+    steps:
+      - name: 📥 Git -- Checkout repository
+        uses: actions/checkout@v7
 
-        - name: 📘 Go -- Set up
-          uses: actions/setup-go@v6
-          with:
-            go-version-file: 'go.mod'
-            cache: true
+      - name: 📘 Go -- Set up
+        uses: actions/setup-go@v7
+        with:
+          go-version-file: "go.mod"
+          cache: true
 
-        - name: 📦 Go -- Install Dependencies
-          run: go mod download
+      - name: 📦 Go -- Install Dependencies
+        run: go mod download
 
-        - name: 🧪 Go -- Unit Tests
-          run: |
-            echo "⚙️ Running unit tests..."
-            if go test -v -race -coverprofile=coverage.out ./...; then
-                echo ""
-                echo "✅ Unit tests passed successfully."
-            else
-                echo ""
-                echo "❌ Unit tests failed. Please fix the errors above."
-                exit 1
-            fi
+      - name: 🧪 Go -- Unit Tests
+        run: |
+          echo "⚙️ Running unit tests..."
+          if go test -v -race -coverprofile=coverage.out ./...; then
+              echo ""
+              echo "✅ Unit tests passed successfully."
+          else
+              echo ""
+              echo "❌ Unit tests failed. Please fix the errors above."
+              exit 1
+          fi
 
-        - name: 📊 Go -- Show Coverage Summary
-          run: |
-            echo "⚙️ Show coverage Summary..."
-            if go tool cover -func=coverage.out; then
-                echo ""
-                echo "✅ Coverage summary displayed successfully."
-            else
-                echo ""
-                echo "❌ Failed to display coverage summary."
-                exit 1
-            fi
+      - name: 📊 Go -- Show Coverage Summary
+        run: |
+          echo "⚙️ Show coverage Summary..."
+          if go tool cover -func=coverage.out; then
+              echo ""
+              echo "✅ Coverage summary displayed successfully."
+          else
+              echo ""
+              echo "❌ Failed to display coverage summary."
+              exit 1
+          fi
